services:
  db:
    image: postgis/postgis
    container_name: postgis
    environment:
      - POSTGRES_PASSWORD=1234
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - ./configs/sql/:/docker-entrypoint-initdb.d/

  

  redis-stack:
    image: redis/redis-stack
    hostname: redis
    ports:
      - "6379:6379"
      - "8001:8001"
    environment:
      REDIS_ARGS: "--requirepass 1234"
    restart: unless-stopped
    # healthcheck:
    #   test: ["CMD-SHELL", "redis-cli -a 1234 ping"]
    #   interval: 10s
    #   timeout: 3s
    #   retries: 3
    #   start_period: 5s
