apiVersion: v1
kind: ConfigMap
metadata:
  name: server-cm
data:
  PGHOST: demodb.cbgykwq4g3t8.eu-central-1.rds.amazonaws.com
  PGPASSWORD: "12345678"
  PGUSER: postgres
  REDIS_HOST: redis-stack.default.svc.cluster.local
  REDIS_PORT: "6379"
  REDIS_PASSWORD: "1234"
  SESSION_SECRET: "1234"
  ENV: prod
  S3_ENDPOINT: 192.168.1.40:9000
  BUCKET_NAME: ahmedhesham301-3akrati
  S3_ACCESS_KEY: rustfsadmin
  S3_SECRET_KEY: rustfsadamin
  # GEMINI_API_KEY: a  # free key
